config/routes.rb
CallMeJoe::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/photos',    to: 'static_pages#photos',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/microposts', to: 'static_pages#micropostsHome', via: 'get'

  resources :sessions,      only: [:new, :create, :destroy]
  resources :posts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :microposts, only: [:create, :destroy, :new]
  

  

end

app/views/layouts/_footer.html.erb
<div id="white">
	<div class ="container">
		<footer class="footer">
		  <nav>
		    <ul class="pull-right">
			    <li><a href="#">Back to top</a></p></li>
		    </ul>
		  </nav>
			<p>&copy; 2014 &middot; <%= link_to "Joe Carlson",root_path %></p>
		</footer>
	</div> 
</div>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41745544-1', 'callmejoe.net');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" position="center"> <%= link_to "call me joe", root_path, id: "logo" %></a>
    </div><!-- /.navbar-header -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav pull-right">
        <% if signed_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Feed", microposts_path %></li>
        <% end %>
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          </ul>
        </li>
        <% else %>
          <!-- <li><%= link_to "Sign in", signin_path %></li> -->
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav><!-- /.navbar -->

app/views/layouts/_loading.html.erb
<div id="loadingMsg">
	<strong class="loading">Loading…</strong>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_simpleloading.html.erb
<div id="loadingMsg">
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <!--Sets Metadata-->
    <%= display_meta_tags %>

    <%= favicon_link_tag '/favicon.ico'%>
    <script type="text/javascript" src="//dl1d2m8ri9v3j.cloudfront.net/releases/1.2.1/tracker.js" data-customer="b138e6102e0245908f0261acd76755d8"></script>

    <link rel="author" href="https://plus.google.com/u/0/+JoeKarlsson/posts"/>

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700|Oswald:400,300,700">

    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

    <!--Recognizes mobile devices-->
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />

    <!--Google Translate https://translate.google.com/manager-->
    <meta name="google-translate-customization" content="5b9be33a7aacbb7-bad5e9e7aa8d26b1-g938f85f48076d2a6-11"></meta>

    <!--CKEditor-->


    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <!--Google analytics-->
    <%= render 'layouts/ga' %>

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <!--Loading Screen-->
    <script>
      window.onload=function(){
      setTimeout(function(){
      $('#loadingMsg').fadeOut( 750, function() {
        // Animation complete.
      });
      }, 0);
      };
    </script>
    <%= render 'layouts/loading' %>

    <%= render 'layouts/header' %>
    <div>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>